# navbar website name
name: peterwjacko
title: Peter W. Jackson

# Website avatars
lightavatar: #/assets/images/light_bauhaus_logo.png
darkavatar: #/assets/images/dark_bauhaus_logo.png

tagline: Personal website and blog
description: Minimalistic Jekyll theme that automatically supports dark and light modes for blogs
url:
baseurl: ""
author: peter-w-jackson
logo: /assets/images/light_bauhaus_logo.png

permalink: /:year/:month/:day/:title/

footer-links:
  email: peterwjacko@protonmail.com
  github: peterwjacko
  linkedin: peterwjacko
  bluesky: peterwjacko.bsky.social
  rss: # just type anything here for a working RSS icon

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
google_analytics: